.TH "RtAudio::RTAUDIO_DEVICE" 3 "22 Jan 2002" "RtAudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RtAudio::RTAUDIO_DEVICE \- 
.SH SYNOPSIS
.br
.PP
\fC#include <RtAudio.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [128]"
.br
.ti -1c
.RI "DEVICE_ID \fBid\fP [2]"
.br
.ti -1c
.RI "bool \fBprobed\fP"
.br
.ti -1c
.RI "int \fBmaxOutputChannels\fP"
.br
.ti -1c
.RI "int \fBmaxInputChannels\fP"
.br
.ti -1c
.RI "int \fBmaxDuplexChannels\fP"
.br
.ti -1c
.RI "int \fBminOutputChannels\fP"
.br
.ti -1c
.RI "int \fBminInputChannels\fP"
.br
.ti -1c
.RI "int \fBminDuplexChannels\fP"
.br
.ti -1c
.RI "bool \fBhasDuplexSupport\fP"
.br
.ti -1c
.RI "int \fBnSampleRates\fP"
.br
.ti -1c
.RI "int \fBsampleRates\fP [MAX_SAMPLE_RATES]"
.br
.ti -1c
.RI "\fBRTAUDIO_FORMAT\fP \fBnativeFormats\fP"
.br
.in -1c
.SH "MEMBER DATA DOCUMENTATION"
.PP 
.SS "char RtAudio::RTAUDIO_DEVICE::name"
.PP
.SS "DEVICE_ID RtAudio::RTAUDIO_DEVICE::id"
.PP
No value reported by \fBgetDeviceInfo\fP(). 
.SS "bool RtAudio::RTAUDIO_DEVICE::probed"
.PP
true if the device capabilities were successfully probed. 
.SS "int RtAudio::RTAUDIO_DEVICE::maxOutputChannels"
.PP
.SS "int RtAudio::RTAUDIO_DEVICE::maxInputChannels"
.PP
.SS "int RtAudio::RTAUDIO_DEVICE::maxDuplexChannels"
.PP
.SS "int RtAudio::RTAUDIO_DEVICE::minOutputChannels"
.PP
.SS "int RtAudio::RTAUDIO_DEVICE::minInputChannels"
.PP
.SS "int RtAudio::RTAUDIO_DEVICE::minDuplexChannels"
.PP
.SS "bool RtAudio::RTAUDIO_DEVICE::hasDuplexSupport"
.PP
true if device supports duplex mode. 
.SS "int RtAudio::RTAUDIO_DEVICE::nSampleRates"
.PP
Number of discrete rates or -1 if range supported. 
.SS "int RtAudio::RTAUDIO_DEVICE::sampleRates"
.PP
Supported rates or (min, max) if range. 
.SS "\fBRTAUDIO_FORMAT\fP RtAudio::RTAUDIO_DEVICE::nativeFormats"
.PP
Bit mask of supported data formats. 

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for RtAudio from the source code.