.TH "RtAudio.h" 3 "22 Jan 2002" "RtAudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RtAudio.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBRtAudioError\fP"
.br
.ti -1c
.RI "class \fBRtAudio\fP"
.br
.ti -1c
.RI "struct \fBRtAudio::RTAUDIO_DEVICE\fP"
.br
.ti -1c
.RI "struct \fBRtAudio::RTAUDIO_STREAM\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__RtAudio_h\fP"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define __RtAudio_h"
.PP
\fBValue:\fP
.PP
.nf

.fi
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for RtAudio from the source code.